# Generated by Django 3.1.2 on 2020-10-13 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='floorNumber',
            new_name='floor',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='roomNumber',
            new_name='room_number',
        ),
    ]
